export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const PERMISSIONS_REPOSITORY = 'PERMISSIONS_REPOSITORY';
export const ROLE_PERMISSION_REPOSITORY = 'ROLE_PERMISSION_REPOSITORY';
